export const rings = [
  {
    id: 1,
    name: "rings",
    image: "products/rings/rings-1.jpg",
    price: 120,
    status: "available",
  },
  {
    id: 2,
    name: "rings",
    image: "products/rings/rings-2.jpg",
    price: 120,
    status: "available",
  },
  {
    id: 3,
    name: "rings",
    image: "products/rings/rings-1.jpg",
    price: 120,
    status: "available",
  },
  {
    id: 4,
    name: "rings",
    image: "products/rings/rings-1.jpg",
    price: 120,
    status: "available",
  },
  {
    id: 5,
    name: "rings",
    image: "products/rings/rings-1.jpg",
    price: 120,
    status: "available",
  },
  {
    id: 6,
    name: "rings",
    image: "products/rings/rings-1.jpg",
    price: 120,
    status: "available",
  },
  {
    id: 7,
    name: "rings",
    image: "products/rings/rings-1.jpg",
    price: 120,
    status: "available",
  },
  {
    id: 8,
    name: "rings",
    image: "products/rings/rings-1.jpg",
    price: 120,
    status: "available",
  },
  {
    id: 9,
    name: "rings",
    image: "products/rings/rings-1.jpg",
    price: 120,
    status: "available",
  },
  {
    id: 10,
    name: "rings",
    image: "products/rings/rings-1.jpg",
    price: 120,
    status: "available",
  },
  {
    id: 11,
    name: "rings",
    image: "products/rings/rings-1.jpg",
    price: 120,
    status: "available",
  },
];

export const necklaces = [
  {
    id: 1,
    name: "necklace",
    image: "products/necklace/necklace-1.webp",
    price: 120,
    status: "available",
  },
  {
    id: 2,
    name: "necklace",
    image: "products/necklace/necklace-2.webp",
    price: 120,
    status: "available",
  },
  {
    id: 4,
    name: "necklace",
    image: "products/necklace/necklace-3.webp",
    price: 120,
    status: "available",
  },
  {
    id: 5,
    name: "necklace",
    image: "products/necklace/necklace-4.webp",
    price: 120,
    status: "available",
  },
  {
    id: 6,
    name: "necklace",
    image: "products/necklace/necklace-1.webp",
    price: 120,
    status: "available",
  },
  {
    id: 7,
    name: "necklace",
    image: "products/necklace/necklace-1.webp",
    price: 120,
    status: "available",
  },
  {
    id: 8,
    name: "necklace",
    image: "products/necklace/necklace-1.webp",
    price: 120,
    status: "available",
  },
  {
    id: 9,
    name: "necklace",
    image: "products/necklace/necklace-1.webp",
    price: 120,
    status: "available",
  },
  {
    id: 10,
    name: "necklace",
    image: "products/necklace/necklace-1.webp",
    price: 120,
    status: "available",
  },
  {
    id: 11,
    name: "necklace",
    image: "products/necklace/necklace-1.webp",
    price: 120,
    status: "available",
  },
];

export const new_products = [
  {
    id: 1,
    name: "necklace",
    image: "products/necklace/necklace-1.webp",
    price: 120,
    status: "available",
  },
  {
    id: 2,
    name: "anklets",
    image: "products/anklets/anklet-1.webp",
    price: 60,
    status: "available",
  },
  {
    id: 3,
    name: "anklet",
    image: "products/anklets/anklet-2.jpg",
    price: 80,
    status: "available",
  },
  {
    id: 4,
    name: "earing",
    image: "products/earings/earings-1.jpg",
    price: 100,
    status: "available",
  },
];
